name: 23MrchllRewardUI
author: Mrchllcloud
editor: Kyz
api: 4.0.0
version: 1.0.0
main: Form\Reward\Main

commands:
  rui:
   description: "Open Reward"
   usage: "/rui"
   permission: rui.use

permissions:
  rui.use:
   description: "Mrchllcloud"
   default: true
